name: quarto
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy
    - pyarrow
    - polars
    - ipykernel
    - jupyter
    - quarto
    - jupyter-cache
    - jupyter_contrib_nbextensions
    - graphviz
    - matplotlib
    - seaborn
    - plotnine
    - altair
    - vega_datasets
    - d3blocks
    - plotly